def sql_create():
    query = '''
CREATE TABLE IF NOT EXISTS zno (
    OUTID uuid,
    Birth int NULL,
    SexTypeName varchar NULL,
    RegName varchar NULL,
    AREANAME varchar NULL,
    TERNAME varchar NULL,
    RegTypeName varchar NULL,
    TerTypeName varchar NULL,
    ClassProfileNAME varchar NULL,
    ClassLangName varchar NULL,
    EONAME varchar NULL,
    EOTypeName varchar NULL,
    EORegName varchar NULL,
    EOAreaName varchar NULL,
    EOTerName varchar NULL,
    EOParent varchar NULL,
    UMLTest varchar NULL,
    UMLTestStatus varchar NULL,
    UMLBall100 float NULL,
    UMLBall12 int NULL,
    UMLBall int NULL,
    UMLAdaptScale int NULL,
    UMLPTName varchar NULL,
    UMLPTRegName varchar NULL,
    UMLPTAreaName varchar NULL,
    UMLPTTerName varchar NULL,
    UkrTest varchar NULL,
    UkrSubTest varchar NULL,
    UkrTestStatus varchar NULL,
    UkrBall100 float NULL,
    UkrBall12 int NULL,
    UkrBall int NULL,
    UkrAdaptScale int NULL,
    UkrPTName varchar NULL,
    UkrPTRegName varchar NULL,
    UkrPTAreaName varchar NULL,
    UkrPTTerName varchar NULL,
    HistTest varchar NULL,
    HistLang varchar NULL,
    HistTestStatus varchar NULL,
    HistBall100 float NULL,
    HistBall12 int NULL,
    HistBall int NULL,
    HistPTName varchar NULL,
    HistPTRegName varchar NULL,
    HistPTAreaName varchar NULL,
    HistPTTerName varchar NULL,
    MathTest varchar NULL,
    MathLang varchar NULL,
    MathTestStatus varchar NULL,
    MathBall100 float NULL,
    MathBall12 int NULL,
    MathDpaLevel varchar NULL,
    MathBall int NULL,
    MathPTName varchar NULL,
    MathPTRegName varchar NULL,
    MathPTAreaName varchar NULL,
    MathPTTerName varchar NULL,
    MathStTest varchar NULL,
    MathStLang varchar NULL,
    MathStTestStatus varchar NULL,
    MathStBall12 int NULL,
    MathStBall int NULL,
    MathStPTName varchar NULL,
    MathStPTRegName varchar NULL,
    MathStPTAreaName varchar NULL,
    MathStPTTerName varchar NULL,
    PhysTest varchar NULL,
    PhysLang varchar NULL,
    PhysTestStatus varchar NULL,
    PhysBall100 float NULL,
    PhysBall12 int NULL,
    PhysBall int NULL,
    PhysPTName varchar NULL,
    PhysPTRegName varchar NULL,
    PhysPTAreaName varchar NULL,
    PhysPTTerName varchar NULL,
    ChemTest varchar NULL,
    ChemLang varchar NULL,
    ChemTestStatus varchar NULL,
    ChemBall100 float NULL,
    ChemBall12 int NULL,
    ChemBall int NULL,
    ChemPTName varchar NULL,
    ChemPTRegName varchar NULL,
    ChemPTAreaName varchar NULL,
    ChemPTTerName varchar NULL,
    BioTest varchar NULL,
    BioLang varchar NULL,
    BioTestStatus varchar NULL,
    BioBall100 float NULL,
    BioBall12 int NULL,
    BioBall int NULL,
    BioPTName varchar NULL,
    BioPTRegName varchar NULL,
    BioPTAreaName varchar NULL,
    BioPTTerName varchar NULL,
    GeoTest varchar NULL,
    GeoLang varchar NULL,
    GeoTestStatus varchar NULL,
    GeoBall100 float NULL,
    GeoBall12 int NULL,
    GeoBall int NULL,
    GeoPTName varchar NULL,
    GeoPTRegName varchar NULL,
    GeoPTAreaName varchar NULL,
    GeoPTTerName varchar NULL,
    EngTest varchar NULL,
    EngTestStatus varchar NULL,
    EngBall100 float NULL,
    EngBall12 int NULL,
    EngDPALevel varchar NULL,
    EngBall int NULL,
    EngPTName varchar NULL,
    EngPTRegName varchar NULL,
    EngPTAreaName varchar NULL,
    EngPTTerName varchar NULL,
    FraTest varchar NULL,
    FraTestStatus varchar NULL,
    FraBall100 float NULL,
    FraBall12 int NULL,
    FraDPALevel varchar NULL,
    FraBall varchar NULL,
    FraPTName varchar NULL,
    FraPTRegName varchar NULL,
    FraPTAreaName varchar NULL,
    FraPTTerName varchar NULL,
    DeuTest varchar NULL,
    DeuTestStatus varchar NULL,
    DeuBall100 float NULL,
    DeuBall12 int NULL,
    DeuDPALevel varchar NULL,
    DeuBall varchar NULL,
    DeuPTName varchar NULL,
    DeuPTRegName varchar NULL,
    DeuPTAreaName varchar NULL,
    DeuPTTerName varchar NULL,
    SpaTest varchar NULL,
    SpaTestStatus varchar NULL,
    SpaBall100 float NULL,
    SpaBall12 int NULL,
    SpaDPALevel varchar NULL,
    SpaBall varchar NULL,
    SpaPTName varchar NULL,
    SpaPTRegName varchar NULL,
    SpaPTAreaName varchar NULL,
    SpaPTTerName varchar NULL,
    YEAR int NULL,
    CONSTRAINT tbl_ZNO_pk PRIMARY KEY (outid)
);
'''
    return query


def sql_variant():  
    query = '''
SELECT RegName, YEAR, MIN(HistBall100) AS MIN_HIST_SCORE
FROM zno
WHERE HistTestStatus = 'Зараховано'
GROUP BY RegName, YEAR;
'''
    return query


def sql_insert(col, val):
    query = f'INSERT INTO zno ({col}) VALUES ({val})'
    return query


def sql_select(table, year):
    query = f'''SELECT COUNT(outID) FROM {table} WHERE year={year}'''
    return query
